---
- hosts: all
  gather_facts: false
  tasks:
  - name: Install basic packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - telnet
      - tmux
      - nc
    register: install_out
...
