---
- hosts: ispw
  gather_facts: false
  tasks:
  - name: Connectivity test from ALL ISPW VMs to AMS-PDR-UCDRELAY
    #when: "'ams_sres_preprod' in inventory_hostname"
    wait_for: host="{{ hosts.ams_pdr_ispw_ucdrelay }}" port="{{ item }}" timeout=5
    register: cmd_output
    changed_when: false
    with_items:
      - "{{ ports.ucd_relay.http_1 }}"
      - "{{ ports.ucd_relay.http_2 }}"
      - "{{ ports.ucd_relay.jms }}"
...
