---
- hosts: shared
  gather_facts: false
  tasks:
  - name: Connectivity test from ALL AMS_SHARED VMs to AMS-SHARED
    #when: "'autobuild' in inventory_hostname"
    wait_for: host="{{ hosts.ams_sres_shared_autobuild }}" port="{{ item }}" timeout=5
    register: cmd_output
    changed_when: false
    with_items:
      - "{{ ports.ucd_relay.http_1 }}"
      - "{{ ports.ucd_relay.http_2 }}"
      - "{{ ports.ucd_relay.jms }}"
...
